<?php
session_start();
require_once __DIR__ . '/../config/DBconnect.php';

$userId = $_SESSION['user_id'] ?? 3;
$invoiceRef = trim($_GET['invoice_ref'] ?? '');

$stmt = $conn->prepare("SELECT i.*, p.payment_method, p.transaction_reference, p.payment_date, u.full_name, u.phone_number, f.flat_number, f.building_block 
                        FROM invoices i
                        LEFT JOIN payments p ON i.invoice_id = p.invoice_id
                        JOIN users u ON i.tenant_id = u.user_id
                        JOIN flats f ON i.flat_id = f.flat_id
                        WHERE i.tenant_id = ? 
                        ORDER BY i.invoice_id DESC LIMIT 1");
$stmt->bind_param("i", $userId);
$stmt->execute();
$inv = $stmt->get_result()->fetch_assoc();

if (!$inv) {
    die("Invoice record not found.");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Invoice #INV-<?= htmlspecialchars($inv['invoice_id']) ?></title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f8fafc; color: #0f172a; padding: 40px; margin: 0; }
    .invoice-card { max-width: 680px; margin: 0 auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 12px; padding: 36px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #10b981; padding-bottom: 18px; margin-bottom: 24px; }
    .title { font-size: 20px; font-weight: 800; color: #10b981; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; font-size: 13.5px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { background: #f1f5f9; padding: 10px; font-size: 11px; text-transform: uppercase; text-align: left; }
    td { padding: 12px 10px; border-bottom: 1px solid #e2e8f0; font-size: 13.5px; }
    .total-row { font-size: 16px; font-weight: 800; }
    .badge { background: #ecfdf5; color: #059669; padding: 4px 8px; border-radius: 4px; font-weight: 800; font-size: 11px; }
    .actions { display: flex; justify-content: flex-end; gap: 10px; margin-top: 24px; }
    .btn { padding: 10px 18px; border-radius: 6px; font-weight: bold; cursor: pointer; border: none; font-size: 13px; }
    .btn-print { background: #10b981; color: #fff; }
    @media print {
      body { background: #fff; padding: 0; }
      .invoice-card { border: none; box-shadow: none; padding: 0; }
      .actions { display: none; }
    }
  </style>
</head>
<body>
  <div class="invoice-card">
    <div class="header">
      <div>
        <div class="title">GREENVIEW HEIGHTS</div>
        <div style="font-size: 12px; color: #64748b;">Official Residence Money Receipt</div>
      </div>
      <div style="text-align: right;">
        <span class="badge">PAID INVOICE</span>
        <div style="font-size: 12px; color: #64748b; margin-top: 4px;">#INV-2026-0<?= htmlspecialchars($inv['invoice_id']) ?></div>
      </div>
    </div>

    <div class="meta-grid">
      <div>
        <strong>Billed To:</strong>
        <div><?= htmlspecialchars($inv['full_name']) ?></div>
        <div>Unit: <?= htmlspecialchars($inv['flat_number']) ?> (Block <?= htmlspecialchars($inv['building_block']) ?>)</div>
        <div>Phone: <?= htmlspecialchars($inv['phone_number']) ?></div>
      </div>
      <div style="text-align: right;">
        <strong>Billing Details:</strong>
        <div>Month: <?= htmlspecialchars($inv['billing_period']) ?></div>
        <div>TrxID: <code><?= htmlspecialchars($inv['transaction_reference'] ?? 'TRX-ONLINE') ?></code></div>
        <div>Method: <?= htmlspecialchars($inv['payment_method'] ?? 'Online Gateway') ?></div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th style="text-align: right;">Amount (BDT)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Core Apartment Rent Portion</td>
          <td style="text-align: right;">৳ <?= number_format($inv['rent_portion'], 2) ?></td>
        </tr>
        <tr>
          <td>Society Maintenance & Security Surcharge</td>
          <td style="text-align: right;">৳ <?= number_format($inv['society_portion'], 2) ?></td>
        </tr>
        <tr>
          <td>Sub-metered Utilities & Common Area Power</td>
          <td style="text-align: right;">৳ <?= number_format($inv['utility_portion'], 2) ?></td>
        </tr>
        <tr class="total-row">
          <td>Total Settled</td>
          <td style="text-align: right; color: #10b981;">৳ <?= number_format($inv['total_amount'], 2) ?></td>
        </tr>
      </tbody>
    </table>

    <div style="font-size: 11.5px; color: #64748b; text-align: center; border-top: 1px dashed #cbd5e1; padding-top: 14px;">
      This is a digitally verified receipt generated by Greenview Heights Society Management.
    </div>

    <div class="actions">
      <button class="btn btn-print" onclick="window.print()">Print / Save as PDF</button>
    </div>
  </div>

  <script>
    window.onload = function() {
      // Auto open print dialog when loaded
      window.print();
    };
  </script>
</body>
</html>